apiVersion: apps/v1
kind: Deployment
metadata:
  name: voyage-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: voyage
  template:
    metadata:
      labels:
        app: voyage
      annotations:
        kubernetes.io/change-cause: "ttl.sh/kubernetes-voyage:v2"
    spec:
      containers:
        - name: voyage
          image: ttl.sh/kubernetes-voyage:v2
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
